packages:
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@storybook/addon-docs@10.4.3'
  - '@storybook/addon-vitest@10.4.3'
  - '@storybook/csf-plugin@10.4.3'
  - '@storybook/react-dom-shim@10.4.3'
  - '@storybook/addon-a11y@10.4.3'
  - '@storybook/builder-vite@10.4.3'
  - '@storybook/web-components-vite@10.4.3'
  - '@storybook/web-components@10.4.3'
  - storybook@10.4.3
